// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Quantum Coin Read API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1
 */

package qcreadapi




type AccountTokenDetailsResponse struct {

	Result AccountTokenDetails `json:"result,omitempty"`
}

// AssertAccountTokenDetailsResponseRequired checks if the required fields are not zero-ed
func AssertAccountTokenDetailsResponseRequired(obj AccountTokenDetailsResponse) error {
	if err := AssertAccountTokenDetailsRequired(obj.Result); err != nil {
		return err
	}
	return nil
}

// AssertAccountTokenDetailsResponseConstraints checks if the values respects the defined constraints
func AssertAccountTokenDetailsResponseConstraints(obj AccountTokenDetailsResponse) error {
	if err := AssertAccountTokenDetailsConstraints(obj.Result); err != nil {
		return err
	}
	return nil
}
