// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * QC Read API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1
 */

package qcreadapi

import (
	"net/http"
	"strings"
)

const API_KEY_HEADER_NAME = "X-Api-Key"
const REQUEST_ID_HEADER_NAME = "X-Request-Id"
const UNAUTHORIZED_ERROR_MSG = "unauthorized"

// ReadApiAPIController binds http requests to an api service and writes the service results to the http response
type ReadApiAPIController struct {
	service ReadApiAPIServicer
	errorHandler ErrorHandler
	corsAllowedOrigins string
	enableAuth bool
	apiKeysMap map[string]bool
}

// ReadApiAPIOption for how the controller is set up.
type ReadApiAPIOption func(*ReadApiAPIController)

// WithReadApiAPIErrorHandler inject ErrorHandler into controller
func WithReadApiAPIErrorHandler(h ErrorHandler) ReadApiAPIOption {
	return func(c *ReadApiAPIController) {
		c.errorHandler = h
	}
}

// NewReadApiAPIController creates a default api controller
func NewReadApiAPIController(s ReadApiAPIServicer, corsAllowedOrigins string, enableAuth bool, apiKeys string, opts ...ReadApiAPIOption) *ReadApiAPIController {
	controller := &ReadApiAPIController{
		service:      s,
		errorHandler: DefaultErrorHandler,
		corsAllowedOrigins: corsAllowedOrigins,
		enableAuth: enableAuth,
		apiKeysMap: make(map[string]bool),
	}

	if len(apiKeys) > 0 {
		apiKeyList := strings.Split(apiKeys, ",")
		for _, key := range apiKeyList {
			if len(key) == 0 {
				continue
			}
			controller.apiKeysMap[key] = true
		}
	}

	for _, opt := range opts {
		opt(controller)
	}

	return controller
}

// Routes returns all the api routes for the ReadApiAPIController
func (c *ReadApiAPIController) Routes() Routes {
	return Routes{
		"GetLatestBlockDetails": Route{
			strings.ToUpper("Get"),
			"/latestblock",
			c.GetLatestBlockDetails,
		},
		"GetBlockDetails": Route{
			strings.ToUpper("Get"),
			"/block/{blockNumber}",
			c.GetBlockDetails,
		},
		"ListBlocks": Route{
			strings.ToUpper("Get"),
			"/blocks/{pageNumber}",
			c.ListBlocks,
		},
		"ListValidators": Route{
			strings.ToUpper("Get"),
			"/validators/{pageNumber}",
			c.ListValidators,
		},
		"GetTransactionDetails": Route{
			strings.ToUpper("Get"),
			"/transaction/{hash}",
			c.GetTransactionDetails,
		},
		"ListTransactions": Route{
			strings.ToUpper("Get"),
			"/transactions/{pageNumber}",
			c.ListTransactions,
		},
		"GetAccountDetails": Route{
			strings.ToUpper("Get"),
			"/account/{address}",
			c.GetAccountDetails,
		},
		"ListAccountTokens": Route{
			strings.ToUpper("Get"),
			"/account/{address}/tokens/{pageNumber}",
			c.ListAccountTokens,
		},
		"GetAccountTokenDetails": Route{
			strings.ToUpper("Get"),
			"/account/{address}/token/{contractAddress}",
			c.GetAccountTokenDetails,
		},
		"ListAccountTransactions": Route{
			strings.ToUpper("Get"),
			"/account/{address}/transactions/{pageNumber}",
			c.ListAccountTransactions,
		},
		"ListAccountPendingTransactions": Route{
			strings.ToUpper("Get"),
			"/account/{address}/transactions/pending/{pageNumber}",
			c.ListAccountPendingTransactions,
		},
		"GetTokenDetails": Route{
			strings.ToUpper("Get"),
			"/token/{contractAddress}",
			c.GetTokenDetails,
		},
		"GetValidatorDetails": Route{
			strings.ToUpper("Get"),
			"/validator/{address}",
			c.GetValidatorDetails,
		},
		"ListStakingReport": Route{
			strings.ToUpper("Get"),
			"/report/staking/{pageNumber}",
			c.ListStakingReport,
		},
		"ListValidatorReport": Route{
			strings.ToUpper("Get"),
			"/report/validator/{pageNumber}",
			c.ListValidatorReport,
		},
		"ListBlockReport": Route{
			strings.ToUpper("Get"),
			"/report/block/{pageNumber}",
			c.ListBlockReport,
		},
		"ListTransactionReport": Route{
			strings.ToUpper("Get"),
			"/report/transaction/{pageNumber}",
			c.ListTransactionReport,
		},
		"ListSpecificValidatorReport": Route{
			strings.ToUpper("Get"),
			"/report/specific-validator/{address}/{pageNumber}",
			c.ListSpecificValidatorReport,
		},
		"GetBlockchainDetailsResponse": Route{
			strings.ToUpper("Get"),
			"/blockchaindetails",
			c.GetBlockchainDetails,
		},
		"QueryDetails": Route{
			strings.ToUpper("Get"),
			"/api",
			c.QueryDetails,
		},
		"ListAccountTokenTransactions": Route{
			strings.ToUpper("Get"),
			"/account/{address}/tokens/transactions/{pageNumber}",
			c.ListAccountTokenTransactions,
		},
	}
}

//(*w).Header().Set("Access-Control-Allow-Headers", "Accept, Content-Type, Content-Length, Accept-Encoding, X-CSRF-Token, Authorization, X-Api-Key")
func (c *ReadApiAPIController) setupCORS(w *http.ResponseWriter, req *http.Request) {
	(*w).Header().Set("Access-Control-Allow-Origin", c.corsAllowedOrigins)
	(*w).Header().Set("Access-Control-Allow-Methods", "GET, OPTIONS")
	(*w).Header().Set("Access-Control-Allow-Headers", "*")
}

func (c *ReadApiAPIController) authorize(req *http.Request) bool {
	if c.enableAuth == false {
		return  true
	}

	if req.Header == nil {
		return  false
	}

	apiKey := req.Header.Get(API_KEY_HEADER_NAME)

	if len(apiKey) == 0 {
		return false
	}

	if c.apiKeysMap[apiKey] == true {
		return true
	}

	return false
}

