// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Quantum Coin Read API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1
 */

package qcreadapi

import "github.com/quantumcoinproject/quantum-coin-go/cachemanager"

type Slashing struct {
	SlashedAccount string `json:"slashedAccount"`
	SlashedAmount  string `json:"slashedAmount"     gencodec:"required"`
}

type BlockConsensusDetails struct {
	BlockProposer        string     `json:"blockProposer"`
	VoteType             string   `json:"voteType"`
	ProposalHash         string     `json:"proposalHash"`
	PrecommitHash        string     `json:"precommitHash"`
	Slashings    		 []Slashing `json:"slashedValidators,omitempty"`
	Rounds               byte 		 `json:"rounds,omitempty"`
	SelectedTransactions []string `json:"selectedTransactions,omitempty"` //this will be a super-set of transactions that actually got executed
	BlockTime            uint64   `json:"blockTime"`                      //as voted
	BlockProposerRewards     string `json:"blockProposerRewards,omitempty"`     //total rewards, blockRewards + txnFeeRewards
	BaseBlockProposerRewards string `json:"baseBlockProposerRewards,omitempty"` //block rewards excluding txn free rewards
	TxnFeeRewards            string `json:"txnFeeRewards,omitempty"`
	BurntTxnFee              string `json:"burntTxnFee,omitempty"`
	SlashAmount              string `json:"slashAmount,omitempty"` //total slash amount
}

type BlockDetails struct {
	// The block number as of which the details were retrieved
	BlockNumber 	 int64 			   `json:"blockNumber,omitempty"`
	Hash             string                `json:"hash,omitempty"`
	ParentHash       string                `json:"parentHash,omitempty"`
	StateRoot        string                `json:"stateRoot,omitempty"`
	TransactionsRoot string                `json:"transactionsRoot,omitempty"`
	ReceiptsRoot     string                `json:"receiptsRoot,omitempty"`
	GasLimit         string                `json:"gasLimit,omitempty"`
	GasUsed          string                `json:"gasUsed,omitempty"`
	BlockTime        uint64                `json:"timestamp,omitempty"`
	TransactionCount uint                  `json:"transactionCount,omitempty"`
	ConsensusDetails BlockConsensusDetails `json:"consensusDetails,omitempty"`
}

// AssertBlockDetailsRequired checks if the required fields are not zero-ed
func AssertBlockDetailsRequired(obj cachemanager.Block) error {
	return nil
}

// AssertBlockDetailsConstraints checks if the values respects the defined constraints
func AssertBlockDetailsConstraints(obj cachemanager.Block) error {
	return nil
}
