// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Quantum Coin Read API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1
 */

package qcreadapi


import (
	"fmt"
)



type TransactionType string

// List of TransactionType
const (
	COIN_TRANSFER TransactionType = "CoinTransfer"
	NEW_TOKEN TransactionType = "NewToken"
	TOKEN_TRANSFER TransactionType = "TokenTransfer"
	NEW_SMART_CONTRACT TransactionType = "NewSmartContract"
	SMART_CONTRACT TransactionType = "SmartContract"
)

// AllowedTransactionTypeEnumValues is all the allowed values of TransactionType enum
var AllowedTransactionTypeEnumValues = []TransactionType{
	"CoinTransfer",
	"NewToken",
	"TokenTransfer",
	"NewSmartContract",
	"SmartContract",
}

// validTransactionTypeEnumValue provides a map of TransactionTypes for fast verification of use input
var validTransactionTypeEnumValues = map[TransactionType]struct{}{
	"CoinTransfer": {},
	"NewToken": {},
	"TokenTransfer": {},
	"NewSmartContract": {},
	"SmartContract": {},
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v TransactionType) IsValid() bool {
	_, ok := validTransactionTypeEnumValues[v]
	return ok
}

// NewTransactionTypeFromValue returns a pointer to a valid TransactionType
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewTransactionTypeFromValue(v string) (TransactionType, error) {
	ev := TransactionType(v)
	if ev.IsValid() {
		return ev, nil
	}

	return "", fmt.Errorf("invalid value '%v' for TransactionType: valid values are %v", v, AllowedTransactionTypeEnumValues)
}



// AssertTransactionTypeRequired checks if the required fields are not zero-ed
func AssertTransactionTypeRequired(obj TransactionType) error {
	return nil
}

// AssertTransactionTypeConstraints checks if the values respects the defined constraints
func AssertTransactionTypeConstraints(obj TransactionType) error {
	return nil
}
