// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
/*
 * QC Read API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1
 */

package main

import (
	"bytes"
	"encoding/json"
	"errors"
	"fmt"
	"io/ioutil"
	"net"
	"net/http"
	"os"
	qcreadapi "github.com/QuantumCoinProject/qc/relay/qcreadapi"
	qcwriteapi "github.com/QuantumCoinProject/qc/relay/qcwriteapi"
	cachemanager "github.com/QuantumCoinProject/qc/cachemanager"
	"strconv"
	"strings"
)

type Config struct {
	Api		string `json:"api"`
	Ip		string `json:"ip"`
	Port	string `json:"port"`
	NodeUrl   string `json:"nodeUrl"`
	CorsAllowedOrigins    string `json:"corsAllowedOrigins"`
	EnableAuth bool `json:"enableAuth"`
	ApiKeys string `json:"apiKeys"`
	CacheUrl string `json:"cacheUrl"`
}

type Configs struct {
	Configs []Config `json:"configs"`
}

func main() {
	if len(os.Args) < 2 {
		printHelp()
		return
	}

	file := os.Args[1]
	configs, err := readConfigJsonDataFile(file)

	if err != nil {
		fmt.Println(err.Error())
		return
	}

	if len(configs) < 1 {
		fmt.Println("Check config json file")
		return
	}

	for _, config := range configs{
		api := config.Api
		ip := config.Ip
		port := config.Port
		nodeUrl := config.NodeUrl
		corsAllowedOrigins := config.CorsAllowedOrigins
		enableAuth := config.EnableAuth
		apiKeys := config.ApiKeys
		cacheUrl := config.CacheUrl

		if net.ParseIP(ip) == nil {
			fmt.Println("Check configuration ip value ", ip)
			return
		}

		if _, err := strconv.Atoi(port); err != nil {
			fmt.Println("Check configuration port value ", port)
			return
		}

		if len(strings.TrimSpace(nodeUrl)) == 0{
			fmt.Println("Check configuration  node Url value", nodeUrl)
			return
		}

		if len(strings.TrimSpace(cacheUrl)) == 0{
			fmt.Println("Check configuration  cache Url value", cacheUrl)
			return
		}

		if strings.EqualFold(api ,"read") {
			go qcReadApi(ip, port, nodeUrl, corsAllowedOrigins,enableAuth,apiKeys, cacheUrl)
		}

		if strings.EqualFold(api ,"write") {
			go qcWriteApi(ip, port, nodeUrl, corsAllowedOrigins,enableAuth,apiKeys)
		}

		go newCachemanager(cacheUrl, nodeUrl)
	}

	fmt.Println("Relay listen and server...")
	<-make(chan int)
}

func qcReadApi(ip string, port string, nodeUrl string, corsAllowedOrigins string, enableAuth bool, apiKeys string, cacheUrl string) {
	ReadApiAPIService := qcreadapi.NewReadApiAPIService(nodeUrl, cacheUrl)
	ReadApiAPIController := qcreadapi.NewReadApiAPIController(ReadApiAPIService, corsAllowedOrigins, enableAuth, apiKeys)
	readRouter := qcreadapi.NewRouter(ReadApiAPIController)

	fmt.Println("Read api server is listening on : ", ip + ":" + port, "nodeUrl" + ":" + nodeUrl, "corsAllowedOrigins" + ":" + corsAllowedOrigins)
	http.ListenAndServe(ip + ":" + port, readRouter)
}

func qcWriteApi(ip string, port string, nodeUrl string, corsAllowedOrigins string, enableAuth bool, apiKeys string) {
	WriteApiAPIService := qcwriteapi.NewWriteApiAPIService(nodeUrl)
	WriteApiAPIController := qcwriteapi.NewWriteApiAPIController(WriteApiAPIService, corsAllowedOrigins, enableAuth, apiKeys)
	writeRouter := qcwriteapi.NewRouter(WriteApiAPIController)

	fmt.Println("Write api server is listening on : ", ip + ":" + port, "nodeUrl" + ":" + nodeUrl, "corsAllowedOrigins" + ":" + corsAllowedOrigins)
	http.ListenAndServe(ip + ":" + port,  writeRouter)
}

func newCachemanager(cacheUrl, nodeUrl string){
	err := cachemanager.NewCacheManager(cacheUrl, nodeUrl)
	fmt.Println("newCachemanager ", err)
}

func readConfigJsonDataFile(filename string)  ([]Config, error) {
	if _, err := os.Stat(filename); err != nil {
		return nil, errors.New("File not found " + filename)
	}

	fileContent, err := os.Open(filename)
	if err != nil {
		return nil, err
	}
	defer fileContent.Close()

	byteResult, err  := ioutil.ReadAll(fileContent)
	if err != nil {
		return nil, err
	}

	byteResult = bytes.TrimPrefix(byteResult, []byte("\xef\xbb\xbf")) // Or []byte{239, 187, 191}

	var configs []Config
	err = json.Unmarshal([]byte(byteResult), &configs)
	if err != nil {
		return nil, err
	}

	return configs, nil
}

func printHelp() {
	fmt.Println("===========")
	fmt.Println("relay config.json")
	fmt.Println("===========")
}
