// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Quantum Coin Read API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1
 */

package qcreadapi




type AccountTokenDetails struct {
	Balance *string `json:"balance,omitempty"`

	ContractAddress *string `json:"contractAddress,omitempty"`
}

// AssertAccountTokenDetailsRequired checks if the required fields are not zero-ed
func AssertAccountTokenDetailsRequired(obj AccountTokenDetails) error {
	return nil
}

// AssertAccountTokenDetailsConstraints checks if the values respects the defined constraints
func AssertAccountTokenDetailsConstraints(obj AccountTokenDetails) error {
	return nil
}
