// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * QC Read API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1
 */

package qcreadapi

import (
	"context"
	"net/http"
)



// ReadApiAPIRouter defines the required methods for binding the api requests to a responses for the ReadApiAPI
// The ReadApiAPIRouter implementation should parse necessary information from the http request,
// pass the data to a ReadApiAPIServicer to perform the required actions, then write the service results to the http response.
type ReadApiAPIRouter interface { 
	GetLatestBlockDetails(http.ResponseWriter, *http.Request)
	GetBlockDetails(http.ResponseWriter, *http.Request)
	ListBlocks(http.ResponseWriter, *http.Request)
	ListValidators(http.ResponseWriter, *http.Request)
	GetTransactionDetails(http.ResponseWriter, *http.Request)
	ListTransactions(http.ResponseWriter, *http.Request)
	GetAccountDetails(http.ResponseWriter, *http.Request)
	ListAccountTokens(http.ResponseWriter, *http.Request)
	GetAccountTokenDetails(http.ResponseWriter, *http.Request)
	ListAccountTransactions(http.ResponseWriter, *http.Request)
	ListAccountPendingTransactions(http.ResponseWriter, *http.Request)
	GetTokenDetails(http.ResponseWriter, *http.Request)
	GetValidatorDetails(http.ResponseWriter, *http.Request)
	ListStakingReport(http.ResponseWriter, *http.Request)
	ListValidatorReport(http.ResponseWriter, *http.Request)
	ListBlockReport(http.ResponseWriter, *http.Request)
	ListTransactionReport(http.ResponseWriter, *http.Request)
	ListSpecificValidatorReport(http.ResponseWriter, *http.Request)
	GetBlockchainDetails(http.ResponseWriter, *http.Request)
	QueryDetails(http.ResponseWriter, *http.Request)
	ListAccountTokenTransactions(http.ResponseWriter, *http.Request)
}


// ReadApiAPIServicer defines the api actions for the ReadApiAPI service
// This interface intended to stay up to date with the openapi yaml used to generate it,
// while the service implementation can be ignored with the .openapi-generator-ignore file
// and updated with the logic required for the API.
type ReadApiAPIServicer interface {
	GetLatestBlockDetails(context.Context) (ImplResponse, error)
	GetBlockDetails(context.Context, int64) (ImplResponse, error)
	ListBlocks(context.Context, int64) (ImplResponse, error)
	ListValidators(context.Context, int64) (ImplResponse, error)
	GetTransactionDetails(context.Context, string) (ImplResponse, error)
	ListTransactions(context.Context, int64) (ImplResponse, error)
	GetAccountDetails(context.Context, string) (ImplResponse, error)
	ListAccountTokens(context.Context, string, int64) (ImplResponse, error)
	GetAccountTokenDetails(context.Context, string, string) (ImplResponse, error)
	ListAccountTransactions(context.Context, string, int64) (ImplResponse, error)
	ListAccountPendingTransactions(context.Context, string, int64) (ImplResponse, error)
	GetTokenDetails(context.Context, string) (ImplResponse, error)
	GetValidatorDetails(context.Context, string) (ImplResponse, error)
	ListStakingReport(context.Context, int64) (ImplResponse, error)
	ListValidatorReport(context.Context, int64) (ImplResponse, error)
	ListBlockReport(context.Context, int64) (ImplResponse, error)
	ListTransactionReport(context.Context, int64) (ImplResponse, error)
	ListSpecificValidatorReport(context.Context, string, int64) (ImplResponse, error)
	GetBlockchainDetails(context.Context) (ImplResponse, error)
	QueryDetails(context.Context, string) (ImplResponse, error)
	ListAccountTokenTransactions(context.Context, string, int64) (ImplResponse, error)
}
