// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * QC Read API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1
 */

package qcreadapi

import (
	"errors"
	"github.com/QuantumCoinProject/qc/common"
	"github.com/QuantumCoinProject/qc/log"
	"github.com/QuantumCoinProject/qc/relay"
	"net/http"
	"strconv"
	"strings"

	"github.com/gorilla/mux"
)

const API_KEY_HEADER_NAME = "X-Api-Key"
const REQUEST_ID_HEADER_NAME = "X-Request-Id"

// ReadApiAPIController binds http requests to an api service and writes the service results to the http response
type ReadApiAPIController struct {
	service ReadApiAPIServicer
	errorHandler ErrorHandler
	corsAllowedOrigins string
	enableAuth bool
	apiKeysMap map[string]bool
}

// ReadApiAPIOption for how the controller is set up.
type ReadApiAPIOption func(*ReadApiAPIController)

// WithReadApiAPIErrorHandler inject ErrorHandler into controller
func WithReadApiAPIErrorHandler(h ErrorHandler) ReadApiAPIOption {
	return func(c *ReadApiAPIController) {
		c.errorHandler = h
	}
}

// NewReadApiAPIController creates a default api controller
func NewReadApiAPIController(s ReadApiAPIServicer, corsAllowedOrigins string, enableAuth bool, apiKeys string, opts ...ReadApiAPIOption) *ReadApiAPIController {
	controller := &ReadApiAPIController{
		service:      s,
		errorHandler: DefaultErrorHandler,
		corsAllowedOrigins: corsAllowedOrigins,
		enableAuth: enableAuth,
		apiKeysMap: make(map[string]bool),
	}

	if len(apiKeys) > 0 {
		apiKeyList := strings.Split(apiKeys, ",")
		for _, key := range apiKeyList {
			if len(key) == 0 {
				continue
			}
			controller.apiKeysMap[key] = true
		}
	}

	for _, opt := range opts {
		opt(controller)
	}

	return controller
}

// Routes returns all the api routes for the ReadApiAPIController
func (c *ReadApiAPIController) Routes() Routes {
	return Routes{
		"GetLatestBlockDetails": Route{
			strings.ToUpper("Get"),
			"/latestblock",
			c.GetLatestBlockDetails,
		},
		"GetAccountDetails": Route{
			strings.ToUpper("Get"),
			"/account/{address}",
			c.GetAccountDetails,
		},
		"GetTransactionDetails": Route{
			strings.ToUpper("Get"),
			"/transaction/{hash}",
			c.GetTransactionDetails,
		},
		"ListAccountTransactions": Route{
			strings.ToUpper("Get"),
			"/account/{address}/transactions/{pageNumber}",
			c.ListAccountTransactions,
		},
		"ListAccountPendingTransactions": Route{
			strings.ToUpper("Get"),
			"/account/{address}/transactions/pending/{pageNumber}",
			c.ListAccountPendingTransactions,
		},
		"GetBlockchainDetailsResponse": Route{
			strings.ToUpper("Get"),
			"/blockchaindetails",
			c.GetBlockchainDetails,
		},
		"QueryDetails": Route{
			strings.ToUpper("Get"),
			"/api",
			c.QueryDetails,
		},
		"GetTokenDetails": Route{
			strings.ToUpper("Get"),
			"/token/{contractAddress}",
			c.GetTokenDetails,
		},
		"GetAccountTokenDetails": Route{
			strings.ToUpper("Get"),
			"/account/{address}/tokens/{contractAddress}",
			c.GetAccountTokenDetails,
		},
	}
}

//(*w).Header().Set("Access-Control-Allow-Headers", "Accept, Content-Type, Content-Length, Accept-Encoding, X-CSRF-Token, Authorization, X-Api-Key")
func (c *ReadApiAPIController) setupCORS(w *http.ResponseWriter, req *http.Request) {
	(*w).Header().Set("Access-Control-Allow-Origin", c.corsAllowedOrigins)
	(*w).Header().Set("Access-Control-Allow-Methods", "GET, OPTIONS")
	(*w).Header().Set("Access-Control-Allow-Headers", "*")
}

func (c *ReadApiAPIController) authorize(req *http.Request) bool {
	if c.enableAuth == false {
		return  true
	}

	if req.Header == nil {
		return  false
	}

	apiKey := req.Header.Get(API_KEY_HEADER_NAME)

	if len(apiKey) == 0 {
		return false
	}

	if c.apiKeysMap[apiKey] == true {
		return true
	}

	return false
}

// GetLatestBlockDetails - Get latest block details
func (c *ReadApiAPIController) GetLatestBlockDetails(w http.ResponseWriter, r *http.Request) {
	log.Info("GetLatestBlockDetails")
	requestId := ""
	if r.Header != nil {
		requestId = r.Header.Get(REQUEST_ID_HEADER_NAME)
	}
	if len(requestId) > 0 {
		log.Info("GetLatestBlockDetails", "requestId", requestId)
	}

	c.setupCORS(&w, r)
	if (*r).Method == "OPTIONS" {
		log.Info("GetLatestBlockDetails OPTIONS", "requestId", requestId)
		return
	}

	if c.authorize(r) == false {
		result := Response(http.StatusUnauthorized, nil)
		// If no error, encode the body and the result code
		_ = EncodeJSONResponse(result.Body, &result.Code, w)

		log.Error("GetLatestBlockDetails", "requestId", requestId, "error", "Unauthorized");
		c.errorHandler(w, r, errors.New("Unauthorized"), &result)
		return
	}

	result, err := c.service.GetLatestBlockDetails(r.Context())
	// If an error occurred, encode the error with the status code
	if err != nil {
		log.Error("GetLatestBlockDetails", "requestId", requestId, "error", err);
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	_ = EncodeJSONResponse(result.Body, &result.Code, w)

	log.Info("GetLatestBlockDetails ok", "requestId", requestId)
}

// GetAccountDetails - Get account details
func (c *ReadApiAPIController) GetAccountDetails(w http.ResponseWriter, r *http.Request) {
	requestId := ""
	if r.Header != nil {
		requestId = r.Header.Get(REQUEST_ID_HEADER_NAME)
	}
	if len(requestId) > 0 {
		log.Info("GetAccountDetails", "requestId", requestId)
	}

	c.setupCORS(&w, r)
	if (*r).Method == "OPTIONS" {
		log.Info("GetAccountDetails OPTIONS", "requestId", requestId)
		return
	}

	if c.authorize(r) == false {
		result := Response(http.StatusUnauthorized, nil)
		// If no error, encode the body and the result code
		_ = EncodeJSONResponse(result.Body, &result.Code, w)

		log.Error("GetAccountDetails", "requestId", requestId, "error", "Unauthorized");

		c.errorHandler(w, r, errors.New("Unauthorized"), &result)
		return
	}

	params := mux.Vars(r)
	addressParam := params["address"]
	if addressParam == "" {
		c.errorHandler(w, r, &RequiredError{"address"}, nil)
		log.Error("GetAccountDetails", "requestId", requestId, "error", "address is empty")
		return
	}

	if !common.IsHexAddressDeep(addressParam) {
		log.Error(relay.MsgAddress, relay.MsgAddress, addressParam, relay.MsgError, relay.ErrInvalidAddress, relay.MsgStatus, http.StatusBadRequest, "requestId", requestId)
		c.errorHandler(w, r, &ParsingError{"address", errors.New("Invalid address")}, nil)
		return
	}

	log.Info("GetAccountDetails", "requestId", requestId, "addressParam", addressParam)
	result, err := c.service.GetAccountDetails(r.Context(), addressParam)
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		log.Error("GetAccountDetails", "requestId", requestId, "error", err)
		return
	}
	// If no error, encode the body and the result code
	_ = EncodeJSONResponse(result.Body, &result.Code, w)

	log.Info("GetAccountDetails ok", "requestId", requestId)
}

// GetTransaction - Get Transaction
func (c *ReadApiAPIController) GetTransactionDetails(w http.ResponseWriter, r *http.Request) {
	requestId := ""
	if r.Header != nil {
		requestId = r.Header.Get(REQUEST_ID_HEADER_NAME)
	}
	if len(requestId) > 0 {
		log.Info("GetTransactionDetails", "requestId", requestId)
	}

	c.setupCORS(&w, r)
	if (*r).Method == "OPTIONS" {
		log.Info("GetTransactionDetails OPTIONS", "requestId", requestId)
		return
	}

	if c.authorize(r) == false {
		result := Response(http.StatusUnauthorized, nil)
		// If no error, encode the body and the result code
		_ = EncodeJSONResponse(result.Body, &result.Code, w)

		log.Error("GetTransactionDetails OPTIONS", "requestId", requestId, "error", "Unauthorized")
		c.errorHandler(w, r, errors.New("Unauthorized"), &result)
		return
	}

	params := mux.Vars(r)
	hashParam := params["hash"]
	if hashParam == "" {
		c.errorHandler(w, r, &RequiredError{"hash"}, nil)
		log.Error("GetTransactionDetails hashParam is empty", "requestId", requestId)
		return
	}

	if !common.IsHexAddressDeep(hashParam) {
		log.Error(relay.MsgAddress, relay.MsgHash, hashParam, relay.MsgError, relay.ErrInvalidHash, relay.MsgStatus, http.StatusBadRequest, "requestId", requestId)
		c.errorHandler(w, r, &ParsingError{"hash", errors.New("Invalid hash")}, nil)
		return
	}

	result, err := c.service.GetTransactionDetails(r.Context(), hashParam)
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		log.Error("GetTransactionDetails", "requestId", requestId, "error", err)
		return
	}

	// If no error, encode the body and the result code
	_ = EncodeJSONResponse(result.Body, &result.Code, w)

	log.Info("GetTransactionDetails ok", "requestId", requestId)
}

func (c *ReadApiAPIController) GetBlockchainDetails(w http.ResponseWriter, r *http.Request) {
	requestId := ""
	if r.Header != nil {
		requestId = r.Header.Get(REQUEST_ID_HEADER_NAME)
	}
	if len(requestId) > 0 {
		log.Info("GetBlockchainDetails", "requestId", requestId)
	}

	c.setupCORS(&w, r)
	if (*r).Method == "OPTIONS" {
		log.Info("GetBlockchainDetails OPTIONS", "requestId", requestId)
		return
	}

	if c.authorize(r) == false {
		result := Response(http.StatusUnauthorized, nil)
		// If no error, encode the body and the result code
		_ = EncodeJSONResponse(result.Body, &result.Code, w)

		log.Error("GetBlockchainDetails", "requestId", requestId, "error", "Unauthorized")
		c.errorHandler(w, r, errors.New("Unauthorized"), &result)
		return
	}

	result, err := c.service.GetBlockchainDetails(r.Context())
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		log.Error("GetBlockchainDetails", "requestId", requestId, "error", err)
		return
	}

	// If no error, encode the body and the result code
	_ = EncodeJSONResponse(result.Body, &result.Code, w)

	log.Info("GetBlockchainDetails ok", "requestId", requestId)
}

// ListAccountTransactions - List account transactions
func (c *ReadApiAPIController) ListAccountTransactions(w http.ResponseWriter, r *http.Request) {
	requestId := ""
	if r.Header != nil {
		requestId = r.Header.Get(REQUEST_ID_HEADER_NAME)
	}
	if len(requestId) > 0 {
		log.Info("ListAccountTransactions", "requestId", requestId)
	}

	c.setupCORS(&w, r)
	if (*r).Method == "OPTIONS" {
		return
	}

	if c.authorize(r) == false {
		result := Response(http.StatusUnauthorized, nil)
		// If no error, encode the body and the result code
		_ = EncodeJSONResponse(result.Body, &result.Code, w)

		log.Error("ListAccountTransactions", "requestId", requestId, "error", "Unauthorized")
		c.errorHandler(w, r, errors.New("Unauthorized"), &result)
		return
	}

	params := mux.Vars(r)
	addressParam := params["address"]
	if addressParam == "" {
		c.errorHandler(w, r, &RequiredError{"address"}, nil)
		log.Error("ListAccountTransactions address is empty", "requestId", requestId)
		return
	}

	if !common.IsHexAddressDeep(addressParam) {
		log.Error(relay.MsgAddress, relay.MsgAddress, addressParam, relay.MsgError, relay.ErrInvalidAddress, relay.MsgStatus, http.StatusBadRequest, "requestId", requestId)
		c.errorHandler(w, r, &ParsingError{"address", errors.New("Invalid address")}, nil)
		return
	}

	pageNumber := int64(-1)
	pageNumberParam := params["pageNumber"]
	var err error
	if len(pageNumberParam) > 0 {
		pageNumber, err = strconv.ParseInt(pageNumberParam, 10, 64)
		if err != nil {
			c.errorHandler(w, r, &ParsingError{"pageNumber", err}, nil)
			log.Error("ListAccountTransactions", "requestId", requestId, "error", "invalid pageNumber")
			return
		}
		if pageNumber <= 0 {
			pageNumber = -1
		}
	}

	result, err := c.service.ListAccountTransactions(r.Context(), addressParam, pageNumber)
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		log.Error("ListAccountTransactions", "requestId", requestId, "error", err)
		return
	}

	// If no error, encode the body and the result code
	_ = EncodeJSONResponse(result.Body, &result.Code, w)

	log.Info("ListAccountTransactions ok", "requestId", requestId)
}

// ListAccountPendingTransactions - List account pending transactions
func (c *ReadApiAPIController) ListAccountPendingTransactions(w http.ResponseWriter, r *http.Request) {
	requestId := ""
	if r.Header != nil {
		requestId = r.Header.Get(REQUEST_ID_HEADER_NAME)
	}
	if len(requestId) > 0 {
		log.Info("ListAccountPendingTransactions", "requestId", requestId)
	}

	c.setupCORS(&w, r)
	if (*r).Method == "OPTIONS" {
		return
	}

	if c.authorize(r) == false {
		result := Response(http.StatusUnauthorized, nil)
		// If no error, encode the body and the result code
		_ = EncodeJSONResponse(result.Body, &result.Code, w)

		log.Error("ListAccountPendingTransactions", "requestId", requestId, "error", "Unauthorized")
		c.errorHandler(w, r, errors.New("Unauthorized"), &result)
		return
	}

	params := mux.Vars(r)
	addressParam := params["address"]
	if addressParam == "" {
		c.errorHandler(w, r, &RequiredError{"address"}, nil)
		log.Error("ListAccountPendingTransactions address is empty", "requestId", requestId)
		return
	}

	if !common.IsHexAddressDeep(addressParam) {
		log.Error(relay.MsgAddress, relay.MsgAddress, addressParam, relay.MsgError, relay.ErrInvalidAddress, relay.MsgStatus, http.StatusBadRequest, "requestId", requestId)
		c.errorHandler(w, r, &ParsingError{"address", errors.New("Invalid address")}, nil)
		return
	}

	pageNumber := int64(-1)
	pageNumberParam := params["pageNumber"]
	var err error
	if len(pageNumberParam) > 0 {
		pageNumber, err = strconv.ParseInt(pageNumberParam, 10, 64)
		if err != nil {
			c.errorHandler(w, r, &ParsingError{"pageNumber", err}, nil)
			log.Error("ListAccountPendingTransactions", "requestId", requestId, "error", "invalid pageNumber")
			return
		}
		if pageNumber <= 0 {
			pageNumber = -1
		}
	}

	result, err := c.service.ListAccountPendingTransactions(r.Context(), addressParam, pageNumber)
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		log.Error("ListAccountPendingTransactions", "requestId", requestId, "error", err)
		return
	}

	// If no error, encode the body and the result code
	_ = EncodeJSONResponse(result.Body, &result.Code, w)

	log.Info("ListAccountPendingTransactions ok", "requestId", requestId)
}

func (c *ReadApiAPIController) QueryDetails(w http.ResponseWriter, r *http.Request) {
	requestId := ""
	if r.Header != nil {
		requestId = r.Header.Get(REQUEST_ID_HEADER_NAME)
	}
	if len(requestId) > 0 {
		log.Info("QueryDetails", "requestId", requestId)
	}

	c.setupCORS(&w, r)
	if (*r).Method == "OPTIONS" {
		return
	}

	if c.authorize(r) == false {
		result := Response(http.StatusUnauthorized, nil)
		// If no error, encode the body and the result code
		_ = EncodeJSONResponse(result.Body, &result.Code, w)

		log.Error("QueryDetails", "requestId", requestId, "error", "Unauthorized")
		c.errorHandler(w, r, errors.New("Unauthorized"), &result)
		return
	}

	log.Error("api", "url", r.URL, "query", r.URL.Query(), "q", r.URL.Query().Get("q"))
	queryTerm := r.URL.Query().Get("q")

	result, err := c.service.QueryDetails(r.Context(), queryTerm)
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		log.Error("QueryDetails", "requestId", requestId, "error", err)
		return
	}

	// If no error, encode the body and the result code
	_ = EncodeTextResponse(result.Body, &result.Code, w)

	log.Info("QueryDetails ok", "requestId", requestId)
}

// GetTokenDetails - Get account details
func (c *ReadApiAPIController) GetTokenDetails(w http.ResponseWriter, r *http.Request) {
	requestId := ""
	if r.Header != nil {
		requestId = r.Header.Get(REQUEST_ID_HEADER_NAME)
	}
	if len(requestId) > 0 {
		log.Info("GetTokenDetails", "requestId", requestId)
	}

	c.setupCORS(&w, r)
	if (*r).Method == "OPTIONS" {
		log.Info("GetTokenDetails OPTIONS", "requestId", requestId)
		return
	}

	if c.authorize(r) == false {
		result := Response(http.StatusUnauthorized, nil)
		// If no error, encode the body and the result code
		_ = EncodeJSONResponse(result.Body, &result.Code, w)

		log.Error("GetTokenDetails", "requestId", requestId, "error", "Unauthorized");

		c.errorHandler(w, r, errors.New("Unauthorized"), &result)
		return
	}

	params := mux.Vars(r)
	contractAddressParam := params["contractAddress"]
	if contractAddressParam == "" {
		c.errorHandler(w, r, &RequiredError{"contractAddress"}, nil)
		log.Error("GetTokenDetails", "requestId", requestId, "error", "contractAddress is empty")
		return
	}

	if !common.IsHexAddressDeep(contractAddressParam) {
		log.Error(relay.MsgContractAddress, relay.MsgContractAddress, contractAddressParam, relay.MsgError, relay.ErrInvalidAddress, relay.MsgStatus, http.StatusBadRequest, "requestId", requestId)
		c.errorHandler(w, r, &ParsingError{"contractAddress", errors.New("Invalid contractAddress")}, nil)
		return
	}

	log.Info("GetTokenDetails", "requestId", requestId, "contractAddressParam", contractAddressParam)
	result, err := c.service.GetTokenDetails(r.Context(), contractAddressParam)
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		log.Error("GetTokenDetails", "requestId", requestId, "error", err)
		return
	}
	// If no error, encode the body and the result code
	_ = EncodeJSONResponse(result.Body, &result.Code, w)

	log.Info("GetTokenDetails ok", "requestId", requestId)
}

// GetAccountTokenDetails - Get account details
func (c *ReadApiAPIController) GetAccountTokenDetails(w http.ResponseWriter, r *http.Request) {
	requestId := ""
	if r.Header != nil {
		requestId = r.Header.Get(REQUEST_ID_HEADER_NAME)
	}
	if len(requestId) > 0 {
		log.Info("GetAccountTokenDetails", "requestId", requestId)
	}

	c.setupCORS(&w, r)
	if (*r).Method == "OPTIONS" {
		log.Info("GetAccountTokenDetails OPTIONS", "requestId", requestId)
		return
	}

	if c.authorize(r) == false {
		result := Response(http.StatusUnauthorized, nil)
		// If no error, encode the body and the result code
		_ = EncodeJSONResponse(result.Body, &result.Code, w)

		log.Error("GetAccountTokenDetails", "requestId", requestId, "error", "Unauthorized");

		c.errorHandler(w, r, errors.New("Unauthorized"), &result)
		return
	}

	params := mux.Vars(r)
	addressParam := params["address"]
	if addressParam == "" {
		c.errorHandler(w, r, &RequiredError{"address"}, nil)
		log.Error("GetAccountTokenDetails", "requestId", requestId, "error", "address is empty")
		return
	}

	if !common.IsHexAddressDeep(addressParam) {
		log.Error(relay.MsgAddress, relay.MsgAddress, addressParam, relay.MsgError, relay.ErrInvalidAddress, relay.MsgStatus, http.StatusBadRequest, "requestId", requestId)
		c.errorHandler(w, r, &ParsingError{"address", errors.New("Invalid address")}, nil)
		return
	}

	contractAddressParam := params["contractAddress"]
	if contractAddressParam == "" {
		c.errorHandler(w, r, &RequiredError{"contractAddress"}, nil)
		log.Error("GetAccountTokenDetails", "requestId", requestId, "error", "contractAddress is empty")
		return
	}

	if !common.IsHexAddressDeep(contractAddressParam) {
		log.Error(relay.MsgContractAddress, relay.MsgContractAddress, contractAddressParam, relay.MsgError, relay.ErrInvalidAddress, relay.MsgStatus, http.StatusBadRequest, "requestId", requestId)
		c.errorHandler(w, r, &ParsingError{"contractAddress", errors.New("Invalid contractAddress")}, nil)
		return
	}

	log.Info("GetAccountTokenDetails", "requestId", requestId, "addressParam", addressParam, "contractAddressParam", contractAddressParam)
	result, err := c.service.GetAccountTokenDetails(r.Context(), addressParam, contractAddressParam)
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		log.Error("GetAccountTokenDetails", "requestId", requestId, "error", err)
		return
	}
	// If no error, encode the body and the result code
	_ = EncodeJSONResponse(result.Body, &result.Code, w)

	log.Info("GetAccountTokenDetails ok", "requestId", requestId)
}