// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Quantum Coin Read API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1
 */

package qcreadapi




type BlockDetailsResponse struct {

	Result BlockDetails `json:"result,omitempty"`
}

// AssertBlockDetailsResponseRequired checks if the required fields are not zero-ed
func AssertBlockDetailsResponseRequired(obj BlockDetailsResponse) error {
	if err := AssertBlockDetailsRequired(obj.Result); err != nil {
		return err
	}
	return nil
}

// AssertBlockDetailsResponseConstraints checks if the values respects the defined constraints
func AssertBlockDetailsResponseConstraints(obj BlockDetailsResponse) error {
	if err := AssertBlockDetailsConstraints(obj.Result); err != nil {
		return err
	}
	return nil
}
