// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Quantum Coin Read API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1
 */

package qcreadapi




type ListAccountTransactionsResponse struct {

	PageCount int64 `json:"pageCount,omitempty"`

	Items []AccountTransactionCompact `json:"items,omitempty"`
}

// AssertListAccountTransactionsResponseRequired checks if the required fields are not zero-ed
func AssertListAccountTransactionsResponseRequired(obj ListAccountTransactionsResponse) error {
	for _, el := range obj.Items {
		if err := AssertAccountTransactionCompactRequired(el); err != nil {
			return err
		}
	}
	return nil
}

// AssertListAccountTransactionsResponseConstraints checks if the values respects the defined constraints
func AssertListAccountTransactionsResponseConstraints(obj ListAccountTransactionsResponse) error {
	for _, el := range obj.Items {
		if err := AssertAccountTransactionCompactConstraints(el); err != nil {
			return err
		}
	}
	return nil
}
