// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Quantum Coin Read API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1
 */

package qcreadapi


import (
	"time"
)



type AccountTransactionCompact struct {

	TxnHash string `json:"txnHash,omitempty"`

	BlockNumber int64 `json:"blockNumber,omitempty"`

	CreatedAt time.Time `json:"createdAt,omitempty"`

	FromAddress *string `json:"fromAddress,omitempty"`

	ToAddress *string `json:"toAddress,omitempty"`

	Value *string `json:"value,omitempty"`

	TxnFee *string `json:"txnFee,omitempty"`

	Status *string `json:"status,omitempty"`

	TransactionType TransactionType `json:"transactionType,omitempty"`

	ErrorReason *string `json:"errorReason,omitempty"`
}

// AssertAccountTransactionCompactRequired checks if the required fields are not zero-ed
func AssertAccountTransactionCompactRequired(obj AccountTransactionCompact) error {
	return nil
}

// AssertAccountTransactionCompactConstraints checks if the values respects the defined constraints
func AssertAccountTransactionCompactConstraints(obj AccountTransactionCompact) error {
	return nil
}
