// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Quantum Coin Read API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1
 */

package qcreadapi




type TokenDetails struct {
	Name *string `json:"name,omitempty"`

	Symbol *string `json:"symbol,omitempty"`

	Owner *string `json:"owner,omitempty"`

	TotalSupply *string `json:"totalSupply,omitempty"`

	Decimals *string `json:"decimals,omitempty"`
}

// AssertTokenDetailsRequired checks if the required fields are not zero-ed
func AssertTokenDetailsRequired(obj TokenDetails) error {
	return nil
}

// AssertTokenDetailsConstraints checks if the values respects the defined constraints
func AssertTokenDetailsConstraints(obj TokenDetails) error {
	return nil
}
