// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Quantum Coin Read API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1
 */

package qcreadapi




type TokenDetailsResponse struct {

	Result TokenDetails `json:"result,omitempty"`
}

// AssertTokenDetailsResponseRequired checks if the required fields are not zero-ed
func AssertTokenDetailsResponseRequired(obj TokenDetailsResponse) error {
	if err := AssertTokenDetailsRequired(obj.Result); err != nil {
		return err
	}
	return nil
}

// AssertTokenDetailsResponseConstraints checks if the values respects the defined constraints
func AssertTokenDetailsResponseConstraints(obj TokenDetailsResponse) error {
	if err := AssertTokenDetailsConstraints(obj.Result); err != nil {
		return err
	}
	return nil
}
