openapi: 3.0.1
info:
  title: Quantum Coin Write API
  version: v1
servers:
  - url: https://sdk.writerelay.quantumcoinapi.com
paths:
  '/transactions':
    post:
      tags:
        - Write
      summary: Send Transaction
      operationId: SendTransaction
      parameters:
        - name: x-request-id
          in: header
          required: false
          description: request id
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                txnData:
                  type: string
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TransactionSummaryResponse'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponseModel'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponseModel'
        '429':
          description: The request was throttled
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponseModel'
        '503':
          description: Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponseModel'
components:
  schemas:
    TransactionSummaryResponse:
      type: object
      properties:
        hash:
          type: string
          nullable: false
        metadata:
          type: object
          nullable: false
      additionalProperties: false
    ErrorResponseModel:
      type: object
      properties:
        message:
          type: string
          nullable: true
        status:
          type: integer
          format: int32
      additionalProperties: false
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: X-API-KEY
security:
  - ApiKeyAuth: [] # use the same name as under securitySchemes