name: Mac Release

on:
  push:
    tags:
    - '*'    

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      # Set fail-fast to false to ensure that feedback is delivered for all matrix combinations. Consider changing this to true when your workflow is stable.
      fail-fast: true

      matrix:
        os: [macos-14]
        build_type: [Release]

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v4
      with:
       go-version: '1.25.3'
        
    - name: Build
      run: |
         brew install coreutils --debug --verbose
         mkdir ${{ github.workspace }}/build && go build -o ${{ github.workspace }}/build ./...

    - name: Create Release
      
      run: |
         mkdir ${{ github.workspace }}/build/release && find ${{ github.workspace }}/build -maxdepth 1 -type f -exec cp {} ${{ github.workspace }}/build/release \;
         cd ${{ github.workspace }}/build/release && tar -czf ${{ github.workspace }}/build/quantumcoin-mac-${{  github.ref_name }}.tar.gz .
         sha256sum ${{ github.workspace }}/build/quantumcoin-mac-${{  github.ref_name }}.tar.gz >${{ github.workspace }}/build/releasehash-quantumcoin-mac-${{  github.ref_name }}.txt
        
         mkdir ${{ github.workspace }}/build/dp-release
         cp ${{ github.workspace }}/build/dp ${{ github.workspace }}/build/dp-release/dp
         cp ${{ github.workspace }}/build/dputil ${{ github.workspace }}/build/dp-release/dputil
         cp ${{ github.workspace }}/build/relay ${{ github.workspace }}/build/dp-release/relay
         cp ${{ github.workspace }}/cmd/relay/config.json ${{ github.workspace }}/build/dp-release/config.json        
         cp ${{ github.workspace }}/consensus/proofofstake/genesis/genesis.json ${{ github.workspace }}/build/dp-release/genesis.json
         cp ${{ github.workspace }}/resources/*.* ${{ github.workspace }}/build/dp-release/
         chmod +x ${{ github.workspace }}/build/dp-release/*.sh 
         rm ${{ github.workspace }}/build/dp-release/connect.cmd
         rm ${{ github.workspace }}/build/dp-release/connectvalidator.cmd
         cd ${{ github.workspace }}/build/dp-release && tar -czf ${{ github.workspace }}/build/qc-release-mac-${{  github.ref_name }}.tar.gz .
         sha256sum ${{ github.workspace }}/build/qc-release-mac-${{  github.ref_name }}.tar.gz >${{ github.workspace }}/build/releasehash-mac-${{  github.ref_name }}.txt
         rm ${{ github.workspace }}/build/dp-release/connect.sh
         rm ${{ github.workspace }}/build/dp-release/connectvalidator.sh
         cp ${{ github.workspace }}/resources/compact/*.sh ${{ github.workspace }}/build/dp-release/
         chmod +x ${{ github.workspace }}/build/dp-release/*.sh
         cd ${{ github.workspace }}/build/dp-release && tar -czf ${{ github.workspace }}/build/qc-release-mac-compact-${{  github.ref_name }}.tar.gz .
         sha256sum ${{ github.workspace }}/build/qc-release-mac-compact-${{  github.ref_name }}.tar.gz >${{ github.workspace }}/build/releasehash-mac-compact-${{  github.ref_name }}.txt
        
         rm ${{ github.workspace }}/build/dp-release/connect.sh
         rm ${{ github.workspace }}/build/dp-release/connectvalidator.sh
         rm ${{ github.workspace }}/build/dp-release/genesis.json
         cp ${{ github.workspace }}/consensus/proofofstake/genesis/devnet/genesis.json ${{ github.workspace }}/build/dp-release/genesis.json
         cp ${{ github.workspace }}/resources/devnet/* ${{ github.workspace }}/build/dp-release/
         chmod +x ${{ github.workspace }}/build/dp-release/*.sh
         cd ${{ github.workspace }}/build/dp-release && tar -czf ${{ github.workspace }}/build/qc-release-mac-devnet-${{  github.ref_name }}.tar.gz .
         sha256sum ${{ github.workspace }}/build/qc-release-mac-devnet-${{  github.ref_name }}.tar.gz >${{ github.workspace }}/build/releasehash-mac-devnet-${{  github.ref_name }}.txt      

    - name: 'Upload Artifact'
      uses: actions/upload-artifact@v4
      with:
        name: qc-release-mac
        path: |
              ${{ github.workspace }}/build/*.*
              
    - name: release
      uses: ncipollo/release-action@v1
      with:
        allowUpdates: true
        artifacts: "build/*.tar.gz,build/*.txt"
